services:
    kolapsis.string.utils:
        class:     Kolapsis\Bundle\AndroidGeneratorBundle\Utils\Inflect
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
